version: '3.8'

services:
  web:
    image: ${DOCKERHUB_USER:-waqas33412345}/cv-web:${VERSION:-latest}
    ports:
      - "1234:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped
